fix ci
Signed-off-by: zwwhdls <weiwei.zhu@juicefs.io>

diff --git a/.github/workflows/juicefs-image.yaml b/.github/workflows/juicefs-image.yaml
--- a/.github/workflows/juicefs-image.yaml
+++ b/.github/workflows/juicefs-image.yaml
@@ -26,7 +26,7 @@ jobs:
         run: |
           JUICEFS_CE_LATEST_VERSION=$(curl -fsSL https://api.github.com/repos/juicedata/juicefs/releases/latest | grep tag_name | grep -oE 'v[0-9]+\.[0-9][0-9]*(\.[0-9]+(-[0-9a-z]+)?)?')
           if [ -z "$JUICEFS_CE_LATEST_VERSION" ]; then
-            echo "Failed to get juicefs ee version"
+            echo "Failed to get juicefs ce version"
             exit 1
           fi
           echo "mount image is juicedata/mount:${JUICEFS_CE_LATEST_VERSION}-$JUICEFS_EE_LATEST_VERSION"
@@ -44,14 +44,20 @@ jobs:
       - name: Build and Push juicefs latest image
         env:
           CEVERSION: latest
-          CEJUICEFS_VERSION: ${{ env.JUICEFS_CE_LATEST_VERSION }}
         run: |
-          image_exist=${{ env.MOUNT_IMAGE_EXIST }}
-          if [ $image_exist == "false" ]; then
-            echo "Build JuiceFS latest image"
-            make -C docker ce-image
-          else
+          JUICEFS_CE_LATEST_VERSION=$(curl -fsSL https://api.github.com/repos/juicedata/juicefs/releases/latest | grep tag_name | grep -oE 'v[0-9]+\.[0-9][0-9]*(\.[0-9]+(-[0-9a-z]+)?)?')
+          if [ -z "$JUICEFS_CE_LATEST_VERSION" ]; then
+            echo "Failed to get juicefs ce version"
+            exit 1
+          fi
+          docker pull juicedata/mount:ce-${JUICEFS_CE_LATEST_VERSION}
+          rst=$?
+          if [ $rst -eq 0 ]; then
             echo "JuiceFS latest image already exists"
+          else
+            echo "Build JuiceFS latest image"
+            export CEJUICEFS_VERSION=${JUICEFS_CE_LATEST_VERSION}
+            make -C docker ce-image
           fi
       - name: Buildx and Push juicefs image
         env:
