update Dockerfile for ee 5.0
Signed-off-by: zwwhdls <weiwei.zhu@juicefs.io>

diff --git a/.github/workflows/juicefs-image.yaml b/.github/workflows/juicefs-image.yaml
--- a/.github/workflows/juicefs-image.yaml
+++ b/.github/workflows/juicefs-image.yaml
@@ -75,7 +75,7 @@ jobs:
         timeout-minutes: 60
         uses: lhotari/action-upterm@v1
 
-  publish-ee-mount-image:
+  publish-ee-4.0-mount-image:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -87,6 +87,51 @@ jobs:
         continue-on-error: true
         run: |
           JUICEFS_EE_LATEST_VERSION=$(curl -sSL https://juicefs.com/static/juicefs -o juicefs-ee && chmod +x juicefs-ee && ./juicefs-ee version | cut -d' ' -f3)
+          if [ -z "$JUICEFS_EE_LATEST_VERSION" ]; then
+            echo "Failed to get juicefs ee version"
+            exit 1
+          fi
+          echo "mount image is juicedata/mount:ee-$JUICEFS_EE_LATEST_VERSION"
+          echo "MOUNT_IMAGE_EXIST=false" >> $GITHUB_ENV
+          echo "JUICEFS_EE_LATEST_VERSION=$JUICEFS_EE_LATEST_VERSION" >> $GITHUB_ENV
+          docker pull juicedata/mount:ee-$JUICEFS_EE_LATEST_VERSION
+          rst=$?
+          if [ $rst -eq 0 ]; then
+            echo "MOUNT_IMAGE_EXIST=true" >> $GITHUB_ENV
+          fi
+      - name: Buildx and Push juicefs image
+        env:
+          EEVERSION: ee-${{ env.JUICEFS_EE_LATEST_VERSION }}
+        run: |
+          image_exist=${{ env.MOUNT_IMAGE_EXIST }}
+          if [ $image_exist == "false" ]; then
+            echo "Build JuiceFS new version image"
+            export DOCKER_CLI_EXPERIMENTAL=enabled
+            docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
+            docker buildx create --use --name mybuilder
+            make -C docker ee-image-buildx
+            make -C docker fuse-ee-image-buildx
+          else
+            echo "JuiceFS mount ee version image already exists"
+          fi
+      - name: Setup upterm session
+        if: ${{ failure() }}
+        timeout-minutes: 60
+        uses: lhotari/action-upterm@v1
+
+  publish-ee-5.0-mount-image:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Login Docker Hub
+        env:
+          PASSWORD: ${{ secrets.DOCKERHUB_FUSE_ACCESS_TOKEN }}
+        run: docker login --username chnliyong --password ${PASSWORD}
+      - name: check latest tag
+        continue-on-error: true
+        run: |
+          curl -sSL https://static.juicefs.com/release/bin_pkgs/latest_stable.tar.gz | tar -xz
+          JUICEFS_EE_LATEST_VERSION=$(grep -oP 'mount_version=\K.*' version.ini)
           if [ -z "$JUICEFS_EE_LATEST_VERSION" ]; then
             echo "Failed to get juicefs ee version"
             exit 1
