add dynamic-provisioning

diff --git a/.github/workflows/k8s-ci.yaml b/.github/workflows/k8s-ci.yaml
--- a/.github/workflows/k8s-ci.yaml
+++ b/.github/workflows/k8s-ci.yaml
@@ -9,5 +9,65 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: Prepare k8s environment
+    - name: Prepare microk8s environment
       run: ${GITHUB_WORKSPACE}/.github/scripts/k8s-deps.sh
+    - name: Deploy JuiceFS CSI
+      run: |
+        sed -i 's@juicedata/juicefs-csi-driver@juicedata/juicefs-csi-driver:nightly@g' ${GITHUB_WORKSPACE}/deploy/k8s.yaml
+        sudo microk8s.kubectl apply -f ${GITHUB_WORKSPACE}/deploy/k8s.yaml
+        # Wait until the deploy finish
+        while true; do
+            echo "Wait JuiceFS CSI to be ready ..."
+            # The juicefs-csi-{node|controller} pods' containers should be all ready
+            count=$(sudo microk8s.kubectl -n kube-system get pods | grep juicefs-csi | awk '{print $2}' | tr '/' '-' | bc | grep -v '^0$' | wc -l)
+            if [ $count = 0 ]; then
+                node_pod=$(sudo microk8s.kubectl -n kube-system get pods -o name | grep juicefs-csi-node | cut -d/ -f2)
+                echo "JUICEFS_CSI_NODE_POD=$node_pod" >> $GITHUB_ENV
+                sudo microk8s.kubectl cp kube-system/$node_pod:/usr/local/bin/juicefs /usr/local/bin/juicefs -c juicefs-plugin \
+                    && juicefs -V
+                echo "JuiceFS CSI is ready."
+                break
+            fi
+            sleep 5
+        done
+    - name: Setup secret env
+      run: |
+        echo "JUICEFS_STORAGE=s3" >> $GITHUB_ENV
+        echo "JUICEFS_BUCKET=http://juicefs-bucket.minio.default.svc.cluster.local:9000" >> $GITHUB_ENV
+        echo "JUICEFS_ACCESS_KEY=minioadmin" >> $GITHUB_ENV
+        echo "JUICEFS_SECRET_KEY=minioadmin" >> $GITHUB_ENV
+        echo "JUICEFS_REDIS_URL=redis://redis.default.svc.cluster.local:6379" >> $GITHUB_ENV
+    - name: Run examples/dynamic-provisioning
+      run: |
+        redis_db=1
+        cd ${GITHUB_WORKSPACE}/examples/dynamic-provisioning
+        printf "name=dynamic-provisioning\nmetaurl=${JUICEFS_REDIS_URL}/%d\naccess-key=${JUICEFS_ACCESS_KEY}\nsecret-key=${JUICEFS_SECRET_KEY}\nstorage=${JUICEFS_STORAGE}\nbucket=${JUICEFS_BUCKET}" $redis_db > secrets.env
+        kustomize build | sudo microk8s.kubectl apply -f -
+        while true; do
+            echo "Wait juicefs-app pod to be ready ..."
+            retval=$(sudo microk8s.kubectl -n kube-system get pods | grep juicefs-app | awk '{print $2}' | tr '/' '-' | bc | grep '^0$')
+            if [ $retval = 0 ]; then
+                echo "Pod juicefs-app is ready."
+                break
+            fi
+            sleep 5
+        done
+        sudo juicefs mount -d "$JUICEFS_REDIS_URL/$redis_db" /jfs
+        pv_count=$(ls /jfs | grep '^pvc-' | wc -l)
+        if [ "x$pv_count" != x1 ]; then
+            echo "Expected 1 PV, got $pv_count"
+            exit 1
+        fi
+        dt1=$(tail -n 1 /jfs/pvc-*/out.txt)
+        if [ -z "$dt1" ]; then
+            echo "Could not read from out.txt"
+            exit 1
+        fi
+        unix_ts1=$(date -d "$dt1" +%s)
+        unix_ts2=$(date +%s)
+        diff=$(echo "$unix_ts2-$unix_ts1" | bc)
+        if [ "$diff" -lt 0 -o "$diff" -gt 15 ]; then
+            echo "Unexpected time skew: $dt1, $(date -d@$unix_ts2 -u)"
+            exit 1
+        fi
+
